# Default values for kuiper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: lfedge/ekuiper
  pullPolicy: IfNotPresent

service:
  ## Service type
  ##
  type: ClusterIP
  ## Port for Kuiper
  ##
  kuiper: 20498
  ## Port for RestApi
  ##
  restapi: 9081
  ## Specify the nodePort(s) value for the LoadBalancer and NodePort service types.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
  ##
  nodePorts:
    kuiper:
    restapi:
  ## Set the LoadBalancer service type to internal only.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
  ##
  # loadBalancerIP:
  ## Load Balancer sources
  ## ref: https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/#restrict-access-for-loadbalancer-service
  ## Example:
  ## loadBalancerSourceRanges:
  ## - 10.10.10.0/24
  ##
  loadBalancerSourceRanges: []
  ## Provide any additional annotations which may be required. Evaluated as a template
  ##
  annotations: {}

persistence:
  enabled: false
  size: 20Mi
  ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
  ## Default: volume.alpha.kubernetes.io/storage-class: default
  # storageClass: "-"
  accessMode: ReadWriteOnce
  ## Existing PersistentVolumeClaims
  ## The value is evaluated as a template
  ## So, for example, the name can depend on .Release or .Chart
  # existingClaim: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

kuiperConfig:
  "client.yaml":
    basic:
      host: 127.0.0.1
      port: 20498
  "kuiper.yaml":
    basic:
      # true|false, with debug level, it prints more debug info
      debug: false
      # true|false, if it's set to true, then the log will be print to console
      consoleLog: false
      # true|false, if it's set to true, then the log will be print to log file
      fileLog: true
      # How many hours to split the file
      rotateTime: 24
      # Maximum file storage hours
      maxAge: 72
      # CLI ip
      ip: 0.0.0.0
      # CLI port
      port: 20498
      # REST service ip
      restIp: 0.0.0.0
      # REST service port
      restPort: 9081
      # true|false, when true, will check the RSA jwt token for rest api
      authentication: false
      #  restTls:
      #    certfile: /var/https-server.crt
      #    keyfile: /var/https-server.key
      # Prometheus settings
      prometheus: false
      prometheusPort: 20499
      # The URL where hosts all of pre-build plugins. By default it's at packages.emqx.net
      pluginHosts: https://packages.emqx.net
      # Whether to ignore case in SQL processing. Note that, the name of customized function by plugins are case-sensitive.
      ignoreCase: true

    # The default options for all rules. Each rule can override this setting by defining its own option
    rule:
      # The qos of the rule. The values can be 0: At most once; 1: At least once; 2: Exactly once
      # If qos is bigger than 0, the checkpoint mechanism will launch to save states so that they can be
      # restored for unintended interrupt or planned restart of the rule. The performance may be affected
      # to enable the checkpoint mechanism
      qos: 0
      # The interval in millisecond to run the checkpoint mechanism.
      checkpointInterval: 300000
      # Whether to send errors to sinks
      sendError: true

    sink:
      # The cache persistence threshold size. If the message in sink cache is larger than 10, then it triggers persistence. If you find
      # the remote system is slow to response, or sink throughput is small, then it's recommend to increase below 2 configurations.
      # More memory is required with the increase of below 2 configurations.
      # If the message count reaches below value, then it triggers persistence.
      cacheThreshold: 10
      # The message persistence is triggered by a ticker, and cacheTriggerCount is for using configure the count to trigger the persistence procedure
      # regardless if the message number reaches cacheThreshold or not. This is to prevent the data won't be saved as the cache never pass the threshold.
      cacheTriggerCount: 15

      # Control to disable cache or not. If it's set to true, then the cache will be disabled, otherwise, it will be enabled.
      disableCache: true

    store:
      #Type of store that will be used for keeping state of the application
      type: sqlite
      redis:
        host: localhost
        port: 6379
        password: kuiper
        #Timeout in ms
        timeout: 1000
      sqlite:
        #Sqlite file name, if left empty name of db will be sqliteKV.db
        name:

    # The settings for portable plugin
    portable:
      # The executable of python. Specify this if you have multiple python instances in your system
      # or other circumstance where the python executable cannot be successfully invoked through the default command.
      pythonBin: python
  "connections/connection.yaml":
    mqtt:
      localConnection: #connection key
        server: "tcp://127.0.0.1:1883"
        username: ekuiper
        password: password
        #certificationPath: /var/kuiper/xyz-certificate.pem
        #privateKeyPath: /var/kuiper/xyz-private.pem.key
        #rootCaPath: /var/kuiper/xyz-rootca.pem
        #insecureSkipVerify: false
        #protocolVersion: 3
        clientid: ekuiper
      cloudConnection: #connection key
        server: "tcp://broker.emqx.io:1883"
        username: user1
        password: password
        #certificationPath: /var/kuiper/xyz-certificate.pem
        #privateKeyPath: /var/kuiper/xyz-private.pem.ke
        #rootCaPath: /var/kuiper/xyz-rootca.pem
        #insecureSkipVerify: false
        #protocolVersion: 3
    edgex:
      redisMsgBus: #connection key
        protocol: redis
        server: 127.0.0.1
        port: 6379
        type: redis
        #  Below is optional configurations settings for mqtt
        #  type: mqtt
        #  optional:
        #    ClientId: client1
        #    Username: user1
        #    Password: password
        #    Qos: 1
        #    KeepAlive: 5000
        #    Retained: true/false
        #    ConnectionPayload:
        #    CertFile:
        #    KeyFile:
        #    CertPEMBlock:
        #    KeyPEMBlock:
        #    SkipCertVerify: true/false
      mqttMsgBus: #connection key
        protocol: tcp
        server: 127.0.0.1
        port: 1883
        topic: events
        type: mqtt
        optional:
          ClientId: "client1"
  "mqtt_source.yaml":
    #Global MQTT configurations
    default:
      qos: 1
      server: "tcp://127.0.0.1:1883"
      #username: user1
      #password: password
      #certificationPath: /var/kuiper/xyz-certificate.pem
      #privateKeyPath: /var/kuiper/xyz-private.pem.key
      #rootCaPath: /var/kuiper/xyz-rootca.pem
      #insecureSkipVerify: false
      #connectionSelector: mqtt.mqtt_conf1
      #kubeedgeVersion:
      #kubeedgeModelFile: ""

    demo_conf: #Conf_key
      qos: 0
      server: "tcp://10.211.55.6:1883"
  "sources/edgex.yaml":
    #Global Edgex configurations
    default:
      protocol: redis
      server: localhost
      port: 5563
      topic: events
      type: redis
      # Could be 'event' or 'request'.
      # If the message is from app service, the message type is an event;
      # Otherwise, if it is from the message bus directly, it should be a request
      messageType: event
      #  Below is optional configurations settings for mqtt
      #  type: mqtt
      #  optional:
      #    ClientId: client1
      #    Username: user1
      #    Password: password
      #    Qos: 1
      #    KeepAlive: 5000
      #    Retained: true/false
      #    ConnectionPayload:
      #    CertFile:
      #    KeyFile:
      #    CertPEMBlock:
      #    KeyPEMBlock:
      #    SkipCertVerify: true/false

    #Override the global configurations
    zmq_conf: #Conf_key
      protocol: tcp
      server: localhost
      port: 5563
      topic: events
      type: zero
      messageType: event

    application_conf: #Conf_key
      protocol: tcp
      server: localhost
      port: 5571
      topic: application
      type: zero
      messageType: request

    mqtt_conf: #Conf_key
      protocol: tcp
      server: 127.0.0.1
      port: 1883
      topic: events
      type: mqtt
      optional:
        KeepAlive: "50"

    share_conf: #Conf_key
      protocol: tcp
      server: 127.0.0.1
      port: 1883
      topic: events
      type: mqtt
      connectionSelector: edgex.redisMsgBus
  "sources/file.yaml":
    default:
      fileType: json
      # The directory of the file relative to kuiper root or an absolute path.
      # Do not include the file name here. The file name should be defined in the stream data source
      path: data
      # The interval between reading the files, time unit is ms. If only read once, set it to 0
      interval: 0

    test:
      path: test
  "sources/httppull.yaml":
    #Global httppull configurations
    default:
      # url of the request server address
      url: http://localhost
      # post, get, put, delete
      method: post
      # The interval between the requests, time unit is ms
      interval: 10000
      # The timeout for http request, time unit is ms
      timeout: 5000
      # If it's set to true, then will compare with last result; If response of two requests are the same, then will skip sending out the result.
      # The possible setting could be: true/false
      incremental: false
      # The body of request, such as '{"data": "data", "method": 1}'
      body: '{}'
      # Body type, none|text|json|html|xml|javascript|form
      bodyType: json
      # Control if to skip the certification verification. If it is set to true, then skip certification verification; Otherwise, verify the certification
      insecureSkipVerify: true
      # HTTP headers required for the request
      headers:
        Accept: application/json

    #Override the global configurations
    application_conf: #Conf_key
      incremental: true
      url: http://localhost:9090/
  "sources/memory.yaml":
  "sources/random.yaml":
    default:
      interval: 1000
      seed: 1
      pattern:
        count: 50
      deduplicate: 0
    ext:
      interval: 100
    dedup:
      interval: 100
      deduplicate: 50
  "sources/zmq.yaml":
    #Global Zmq configurations
    default:
      server: tcp://127.0.0.1:5563
