# Default values for kuiper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: lfedge/ekuiper
  pullPolicy: IfNotPresent

service:
  ## Service type
  ##
  type: ClusterIP

  ## @param service.ports.kuiper eKuiper port
  ## @param service.ports.restapi eKuiper API port
  ##
  ports:
    kuiper: 20498
    restapi: 9081

  ## Service ports name
  ## @param service.portNames.kuiper eKuiper portname
  ## @param service.portNames.restapi eKuiper API port name
  ##
  portNames:
    kuiper: "kuiper"
    restapi: "restapi"

  ## Specify the nodePort(s) value for the LoadBalancer and NodePort service types.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
  ##
  nodePorts:
    kuiper:
    restapi:
  ## Set the LoadBalancer service type to internal only.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
  ##
  # loadBalancerIP:
  ## Load Balancer sources
  ## ref: https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/#restrict-access-for-loadbalancer-service
  ## Example:
  ## loadBalancerSourceRanges:
  ## - 10.10.10.0/24
  ##
  loadBalancerSourceRanges: []
  ## Provide any additional annotations which may be required. Evaluated as a template
  ##
  annotations: {}

persistence:
  enabled: true
  size: 20Mi
  storageClassName: ""
  accessMode: ReadWriteOnce
  ## Existing PersistentVolumeClaims
  ## The value is evaluated as a template
  ## So, for example, the name can depend on .Release or .Chart
  existingClaim: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

## @param clusterDomain Kubernetes Cluster Domain
##
clusterDomain: cluster.local

## Enable encryption to eKuiper
## @param tls.enabled Enable TLS support on eKuiper
## @param tls.autoGenerated Generate automatically self-signed TLS certificates
## @param tls.caCertificate Certificate Authority (CA) bundle content
## @param tls.serverCertificate Server certificate content
## @param tls.serverKey Server private key content
## @param tls.existingSecret Existing secret with certificate content to eKuiper credentials
## @param tls.existingSecretFullChain Whether or not the existing secret contains the full chain in the certificate (`tls.crt`). Will be used in place of `ca.cert` if `true`.
##
tls:
  enabled: false
  autoGenerated: false
  caCertificate: |-
  serverCertificate: |-
  serverKey: |-
  existingSecret: ""
  existingSecretFullChain: false

kuiperConfig:
  "kuiper.yaml":
    basic:
      # true|false, with debug level, it prints more debug info
      debug: false
      # true|false, if it's set to true, then the log will be print to console
      consoleLog: false
      # true|false, if it's set to true, then the log will be print to log file
      fileLog: true
      # How many hours to split the file
      rotateTime: 24
      # Maximum file storage hours
      maxAge: 72
      # CLI ip
      ip: 0.0.0.0
      # CLI port
      port: 20498
      # REST service ip
      restIp: 0.0.0.0
      # REST service port
      restPort: 9081
      # true|false, when true, will check the RSA jwt token for rest api
      authentication: false
      #  restTls:
      #    certfile: /var/https-server.crt
      #    keyfile: /var/https-server.key
      # Prometheus settings
      prometheus: false
      prometheusPort: 20499
      # The URL where hosts all of pre-build plugins. By default it's at packages.emqx.net
      pluginHosts: https://packages.emqx.net
      # Whether to ignore case in SQL processing. Note that, the name of customized function by plugins are case-sensitive.
      ignoreCase: true

    # The default options for all rules. Each rule can override this setting by defining its own option
    rule:
      # The qos of the rule. The values can be 0: At most once; 1: At least once; 2: Exactly once
      # If qos is bigger than 0, the checkpoint mechanism will launch to save states so that they can be
      # restored for unintended interrupt or planned restart of the rule. The performance may be affected
      # to enable the checkpoint mechanism
      qos: 0
      # The interval in millisecond to run the checkpoint mechanism.
      checkpointInterval: 300000
      # Whether to send errors to sinks
      sendError: true

    sink:
      # The cache persistence threshold size. If the message in sink cache is larger than 10, then it triggers persistence. If you find
      # the remote system is slow to response, or sink throughput is small, then it's recommend to increase below 2 configurations.
      # More memory is required with the increase of below 2 configurations.
      # If the message count reaches below value, then it triggers persistence.
      cacheThreshold: 10
      # The message persistence is triggered by a ticker, and cacheTriggerCount is for using configure the count to trigger the persistence procedure
      # regardless if the message number reaches cacheThreshold or not. This is to prevent the data won't be saved as the cache never pass the threshold.
      cacheTriggerCount: 15

      # Control to disable cache or not. If it's set to true, then the cache will be disabled, otherwise, it will be enabled.
      disableCache: true

    store:
      #Type of store that will be used for keeping state of the application
      type: sqlite
      redis:
        host: localhost
        port: 6379
        password: kuiper
        #Timeout in ms
        timeout: 1000
      sqlite:
        #Sqlite file name, if left empty name of db will be sqliteKV.db
        name:

    # The settings for portable plugin
    portable:
      # The executable of python. Specify this if you have multiple python instances in your system
      # or other circumstance where the python executable cannot be successfully invoked through the default command.
      pythonBin: python

# TODO
## remove this when the mqtt_source configmap is available
kuiperEnv:
  enabled: true
  key:
    mqttDefaultServer: MQTT_SOURCE__DEFAULT__SERVER

  value:
    mqttDefaultServer: "tcp://broker.emqx.io:1883"
