version: '3.4'

services:
  manager:
    image: emqx/ekuiper-manager:1.5.0
    container_name: ekuiper-manager
    ports:
      - "9082:9082"
  ekuiper:
    image: lfedge/ekuiper:1.5.0-slim
    ports:
      - "9081:9081"
      - "127.0.0.1:20498:20498"
    container_name: manager-ekuiper
    hostname: manager-ekuiper
    environment:
      MQTT_SOURCE__DEFAULT__SERVER: "tcp://syno.home:1883"
      KUIPER__BASIC__CONSOLELOG: "true"
      KUIPER__BASIC__IGNORECASE: "false"
    volumes:
      - nng-ipc:/tmp
  neuron:
    image: neugates/neuron:2.0.1
    ports:
      - "127.0.0.1:7001:7001"
      - "127.0.0.1:7000:7000"
    container_name: manager-neuron
    hostname: manager-neuron
    volumes:
      - nng-ipc:/tmp

volumes:
  nng-ipc: