version: '3.4'

services:
  manager:
    image: emqx/ekuiper-manager:1.9
    container_name: ekuiper-manager
    ports:
      - "9082:9082"
  ekuiper:
    image: lfedge/ekuiper:1.9
    ports:
      - "9081:9081"
      - "127.0.0.1:20498:20498"
    container_name: ekuiper
    hostname: ekuiper
    environment:
      MQTT_SOURCE__DEFAULT__SERVER: "tcp://mybroker:1883"
      KUIPER__BASIC__CONSOLELOG: "true"
      KUIPER__BASIC__IGNORECASE: "false"
      # The default neuron url. Change it if you want to use another port.
      SOURCES__NEURON__DEFAULT__URL: "tcp://neuron:7081"
    volumes:
      - /tmp/data:/kuiper/data
      - /tmp/log:/kuiper/log
      # Enable the following line if you want to use the IPC mode to connect to earlier version of neuron
      # - nng-ipc:/tmp
  neuron:
    image: neugates/neuron:2.4.0
    ports:
      - "7001:7001"
      # The default port to communicate with eKuiper. Change it if you want to use another port.
      - "7081:7081"
    container_name: neuron
    hostname: neuron
    volumes:
      - /tmp/neuron/data:/opt/neuron/persistence
      # Enable the following line if you want to use the IPC mode to connect to earlier version of eKuiper
      # - nng-ipc:/tmp

# Enable the following lines if you want to use the IPC mode to connect to earlier version of eKuiper and neuron
# volumes:
#  nng-ipc: