name: Run fvt tests

on:
    push:
    pull_request:
    release:
        types:
            - published
            - prereleased

jobs:
    fvt_tests:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/setup-go@v1
          with:
            go-version: '1.11.5'
        - uses: actions/setup-java@v1
          with:
            java-version: '8' # The JDK version to make available on the path.
            java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
            architecture: x64 # (x64 or x86) - defaults to x64
        - name: set up jmeter
          env:
            JMETER_VERSION: 5.2.1
          run: |
            wget -O /tmp/apache-jmeter.tgz http://mirror.bit.edu.cn/apache//jmeter/binaries/apache-jmeter-$JMETER_VERSION.tgz
            cd /tmp && tar -xvf apache-jmeter.tgz
            echo "jmeter.save.saveservice.output_format=xml" >> /tmp/apache-jmeter-$JMETER_VERSION/user.properties
            echo "jmeter.save.saveservice.response_data.on_error=true" >> /tmp/apache-jmeter-$JMETER_VERSION/user.properties
            wget -O /tmp/apache-jmeter-$JMETER_VERSION/lib/ext/mqtt-xmeter-1.13-jar-with-dependencies.jar https://github.com/emqx/mqtt-jmeter/raw/master/Download/v1.13.0/mqtt-xmeter-1.13-jar-with-dependencies.jar
            ln -s /tmp/apache-jmeter-$JMETER_VERSION /opt/jmeter
        - name: install emqx
          env:
            EMQX_VERSION: v4.0.2
          run: |
            wget -O emqx.deb https://www.emqx.io/downloads/broker/v4.0.2/emqx-ubuntu18.04-${EMQX_VERSION}_amd64.deb
            sudo dpkg -i emqx.deb
        - uses: actions/checkout@v2
        - name: build kuiper
          run: make
        - name: run emqx and kuiper
          run: sudo ./fvt_scripts/setup_env.sh
        - name: run fvt tests
          timeout-minutes: 5
          run: ./fvt_scripts/run_jmeter.sh
        - uses: actions/upload-artifact@v1
          with:
            name: jmeter.log
            path: ./jmeter.log
        - name: checkout out
          run: |
            sudo apt update && sudo apt install -y libxml2-utils
            if [ "$(xmllint --format --xpath '/testResults/sample/@rc' $(ls *.jtl) | sed -r 's/ /\n/g;' | sort -u | grep -E 'rc=\"[45][0-9][0-9]\"|rc=\"\"')" != "" ]; then
                echo -e "---------------------------------------------\n"
                echo "FVT tests error"
                exit 1
            fi
            
