name: Lint

concurrency:
  group: lint-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read

jobs:
  check_licenses:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Check licenses
        run: |
          go install github.com/google/go-licenses@latest
          $(go env GOPATH)/bin/go-licenses check ./... --disallowed_types forbidden,restricted,unknown --ignore modernc.org/mathutil

  golangci_lint:
    runs-on: ubuntu-latest
    needs:
      - check_licenses
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get install -y --no-install-recommends pkg-config libzmq3-dev

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: "--out-${NO_FUTURE}format line-number"

      - name: golangci-lint (extensions)
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: extensions
          args: "--out-${NO_FUTURE}format line-number"

      - name: golangci-lint (tools/kubernetes)
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: tools/kubernetes
          args: "--out-${NO_FUTURE}format line-number"

      - name: golangci-lint (sdk/go)
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: sdk/go
          args: "--out-${NO_FUTURE}format line-number"
